
        ServerAdmin webmaster@rechnername
        DocumentRoot /var/www/html
        
        <Directory / >
                Options FollowSymLinks
                AllowOverride None
        </Directory>

        <Directory /var/www/html >
                Options -Indexes +FollowSymLinks +MultiViews
                AllowOverride All
                Require all granted
        </Directory>


     <Proxy balancer://cis_limited>
            BalancerMember http://localhost:21300
            ProxySet lbmethod=bybusyness
     </Proxy>
     <Proxy balancer://cis_extdb>
            BalancerMember http://localhost:21400
            BalancerMember http://localhost:21410
            ProxySet lbmethod=bybusyness
     </Proxy>
     <Proxy balancer://cis_normal>
             BalancerMember http://localhost:21010
             ProxySet lbmethod=bybusyness
     </Proxy>
     <Proxy balancer://cis_memory>
             BalancerMember http://localhost:21200
             BalancerMember http://localhost:21210
             ProxySet lbmethod=bybusyness
     </Proxy>
     <Proxy balancer://cis_long>
            BalancerMember http://localhost:21100
            ProxySet lbmethod=bybusyness
     </Proxy>

     ProxyPass /cis/v1/normal balancer://cis_long/cis/v1/normal
     ProxyPass /cis/v1/long balancer://cis_long/cis/v1/long
     ProxyPass /cis/v1/memory balancer://cis_memory/cis/v1/memory
     ProxyPass /cis/v1/limited balancer://cis_limited/cis/v1/limited
     ProxyPass /cis/v1/extdb balancer://cis_long/cis/v1/extdb


     # Einstellungen für die VHOSTS von RabbitMQ - Application Events delivered via WebSocket
     ProxyPass         /vhost-events    ws://rechnername-rabbitmq:15675/ws
     ProxyPassReverse  /vhost-events    ws://rechnername-rabbitmq:15675/ws

    RewriteEngine on
    #RewriteCond %{REQUEST_URI} ^/$

